
# SEO settings
title: "Gabriel Sirilan"
#title2: "space" # default: ""
#description: "Just another minimalist Jekyll theme that focuses on technical writing."
#keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://gsiris.github.io # site url
#baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

#google_analytics: UA-XXXXX-XX
#repo: http://github.com/heiswayi/thinkspace
#disqus_shortname: "heiswayi"
twitter_username: "gabrielsiris"
#comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Gabriel Sirilan"
  job      : "student"
  bio      : "Still doing school-related stuff. I'll start soon."
#  thumb    : /images/author.jpg
  email    : gasirilan@gmail.com
  url      : http://gsiris.github.io
  github   : http://github.com/gsiris
  twitter  : http://twitter.com/gabrielsiris
  #facebook : https://www.facebook.com/profile.php?id=1257583160
  # linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
#twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
